(function () {
  "use strict";

  window.UTAH_PARK_GROUPS = [
    {
      id: "national-parks",
      shortLabel: "National Parks",
      title: "Utah National Parks",
      countLabel: "5 parks",
      image: "national-parks.webp",
      imageAlt: "Illustrated Utah red-rock panorama with an arch, hoodoos, canyons, cliffs, and a river",
      description: "Utah’s Mighty Five, each shaped by a different combination of rock, water, wind, and time.",
      sourceLabel: "National Park Service: Utah",
      sourceUrl: "https://www.nps.gov/state/ut/index.htm",
    },
    {
      id: "national-monuments",
      shortLabel: "Monuments",
      title: "Utah National Monuments",
      countLabel: "9 monuments",
      image: "national-monuments.webp",
      imageAlt: "Illustrated Utah protected landscape with twin buttes, a natural bridge, cliffs, ruins, and fossils",
      description: "Nine federally designated landscapes preserving geology, fossils, caves, and cultural history.",
      sourceLabel: "NPS and BLM Utah monument directories",
      sourceUrl: "https://www.blm.gov/programs/national-conservation-lands/utah",
    },
    {
      id: "state-parks",
      shortLabel: "State Parks",
      title: "Utah State Parks",
      countLabel: "46 parks",
      image: "state-parks.webp",
      imageAlt: "Illustrated Utah landscape with a mountain lake, bison, sandstone, hoodoos, camping, and dinosaur tracks",
      description: "Forty-six recreation areas, reservoirs, museums, trails, historic sites, and remarkable landscapes.",
      sourceLabel: "Official Utah State Parks directory",
      sourceUrl: "https://stateparks.utah.gov/parks/",
    },
  ];

  window.UTAH_PARKS = [
    {
      id: "arches",
      group: "national-parks",
      name: "Arches National Park",
      region: "Near Moab",
      clue: "More than 2,000 documented natural stone arches, plus fins and balanced rocks.",
    },
    {
      id: "bryce-canyon",
      group: "national-parks",
      name: "Bryce Canyon National Park",
      region: "Southwestern Utah",
      clue: "The world’s largest concentration of hoodoos rises from a high plateau.",
    },
    {
      id: "canyonlands",
      group: "national-parks",
      name: "Canyonlands National Park",
      region: "Near Moab",
      clue: "The Colorado and Green rivers divide this canyon wilderness into four districts.",
    },
    {
      id: "capitol-reef",
      group: "national-parks",
      name: "Capitol Reef National Park",
      region: "Near Torrey",
      clue: "The Waterpocket Fold forms a nearly 100-mile wrinkle in the Earth.",
    },
    {
      id: "zion",
      group: "national-parks",
      name: "Zion National Park",
      region: "Near Springdale",
      clue: "Towering cream, pink, and red cliffs frame a deep canyon and the Narrows.",
    },

    {
      id: "bears-ears",
      group: "national-monuments",
      name: "Bears Ears National Monument",
      region: "Southeastern Utah",
      clue: "Twin buttes overlook a vast cultural landscape with deep ties to Tribal Nations.",
    },
    {
      id: "cedar-breaks",
      group: "national-monuments",
      name: "Cedar Breaks National Monument",
      region: "Near Cedar City",
      clue: "A half-mile-deep amphitheater sits above 10,000 feet among bristlecone pines.",
    },
    {
      id: "dinosaur",
      group: "national-monuments",
      name: "Dinosaur National Monument",
      region: "Utah and Colorado",
      clue: "A quarry wall preserves dinosaur fossils in place above the Green River country.",
    },
    {
      id: "grand-staircase",
      group: "national-monuments",
      name: "Grand Staircase–Escalante National Monument",
      region: "Southern Utah",
      clue: "Nearly 1.9 million acres of cliffs, plateaus, canyons, badlands, and fossil beds.",
    },
    {
      id: "hovenweep",
      group: "national-monuments",
      name: "Hovenweep National Monument",
      region: "Utah and Colorado",
      clue: "Ancestral Puebloan stone towers stand along canyon rims and atop boulders.",
    },
    {
      id: "jurassic",
      group: "national-monuments",
      name: "Jurassic National Monument",
      region: "Near Cleveland",
      clue: "The Cleveland-Lloyd Dinosaur Quarry holds a dense concentration of Jurassic bones.",
    },
    {
      id: "natural-bridges",
      group: "national-monuments",
      name: "Natural Bridges National Monument",
      region: "Near Blanding",
      clue: "Sipapu, Kachina, and Owachomo are three bridges carved by moving water.",
    },
    {
      id: "rainbow-bridge",
      group: "national-monuments",
      name: "Rainbow Bridge National Monument",
      region: "Near Lake Powell",
      clue: "One of the world’s largest known natural bridges is sacred to neighboring Tribal Nations.",
    },
    {
      id: "timpanogos-cave",
      group: "national-monuments",
      name: "Timpanogos Cave National Monument",
      region: "American Fork Canyon",
      clue: "A steep trail leads to decorated underground rooms inside Mount Timpanogos.",
    },

    {
      id: "anasazi",
      group: "state-parks",
      name: "Anasazi State Park Museum",
      region: "Boulder",
      clue: "A museum and village site interpret one of the largest Ancestral Puebloan communities west of the Colorado River.",
    },
    {
      id: "antelope-island",
      group: "state-parks",
      name: "Antelope Island State Park",
      region: "Great Salt Lake",
      clue: "Bison, beaches, and backcountry trails occupy the Great Salt Lake’s largest island.",
    },
    {
      id: "bear-lake",
      group: "state-parks",
      name: "Bear Lake State Park",
      region: "Utah–Idaho line",
      clue: "Suspended minerals give this mountain lake its famous turquoise color.",
    },
    {
      id: "camp-floyd",
      group: "state-parks",
      name: "Camp Floyd State Park Museum",
      region: "Fairfield",
      clue: "Army troops, stagecoaches, and the Pony Express crossed paths at this historic site.",
    },
    {
      id: "coral-pink",
      group: "state-parks",
      name: "Coral Pink Sand Dunes State Park",
      region: "Near Kanab",
      clue: "Wind shifts mountains of warm coral-colored sand across the landscape.",
    },
    {
      id: "dead-horse-point",
      group: "state-parks",
      name: "Dead Horse Point State Park",
      region: "Near Moab",
      clue: "A high desert overlook stands 2,000 feet above a Colorado River gooseneck.",
    },
    {
      id: "deer-creek",
      group: "state-parks",
      name: "Deer Creek State Park",
      region: "Heber Valley",
      clue: "A reservoir below Mount Timpanogos draws boaters, anglers, and windsurfers.",
    },
    {
      id: "east-canyon",
      group: "state-parks",
      name: "East Canyon State Park",
      region: "Morgan County",
      clue: "A mountain reservoir combines boating and camping with pioneer-trail history.",
    },
    {
      id: "echo",
      group: "state-parks",
      name: "Echo State Park",
      region: "Summit County",
      clue: "A reservoir near the historic Echo Canyon corridor offers boating and camping.",
    },
    {
      id: "edge-of-cedars",
      group: "state-parks",
      name: "Edge of the Cedars State Park Museum",
      region: "Blanding",
      clue: "A major Four Corners collection of Ancestral Puebloan pottery sits beside an authentic village.",
    },
    {
      id: "escalante-petrified",
      group: "state-parks",
      name: "Escalante Petrified Forest State Park",
      region: "Escalante",
      clue: "Trails through petrified wood rise above Wide Hollow Reservoir.",
    },
    {
      id: "flight-park",
      group: "state-parks",
      name: "Flight Park State Recreation Area",
      region: "Point of the Mountain",
      clue: "A world-known training site launches hang gliders and paragliders into reliable winds.",
    },
    {
      id: "starvation",
      group: "state-parks",
      name: "Fred Hayes State Park at Starvation",
      region: "Near Duchesne",
      clue: "A sprawling reservoir offers fishing, boating, camping, and access to off-highway trails.",
    },
    {
      id: "fremont-indian",
      group: "state-parks",
      name: "Fremont Indian State Park and Museum",
      region: "Sevier County",
      clue: "A museum preserves artifacts and rock art from a large Fremont village uncovered during I-70 construction.",
    },
    {
      id: "frontier-homestead",
      group: "state-parks",
      name: "Frontier Homestead State Park Museum",
      region: "Cedar City",
      clue: "Horse-drawn wagons and historic buildings tell stories of pioneer and industrial life.",
    },
    {
      id: "goblin-valley",
      group: "state-parks",
      name: "Goblin Valley State Park",
      region: "Emery County",
      clue: "Thousands of whimsical sandstone goblins make the valley feel like another planet.",
    },
    {
      id: "goosenecks",
      group: "state-parks",
      name: "Goosenecks State Park",
      region: "San Juan County",
      clue: "The San Juan River twists through deep entrenched meanders below a desert overlook.",
    },
    {
      id: "great-salt-lake",
      group: "state-parks",
      name: "Great Salt Lake State Park",
      region: "Salt Lake County",
      clue: "A marina provides boating access and sunset views across Utah’s saline lake.",
    },
    {
      id: "green-river",
      group: "state-parks",
      name: "Green River State Park",
      region: "Green River",
      clue: "Cottonwoods and a riverside launch serve boaters headed toward Labyrinth Canyon.",
    },
    {
      id: "gunlock",
      group: "state-parks",
      name: "Gunlock State Park",
      region: "Washington County",
      clue: "A warm desert reservoir offers boating, swimming, and occasional seasonal waterfalls.",
    },
    {
      id: "union-pacific-trail",
      group: "state-parks",
      name: "Historic Union Pacific Rail Trail State Park",
      region: "Park City to Echo",
      clue: "A 28-mile nonmotorized rail trail links Park City with Echo Reservoir.",
    },
    {
      id: "huntington",
      group: "state-parks",
      name: "Huntington State Park",
      region: "Emery County",
      clue: "Cinnamon-colored buttes surround a quiet warm-water reservoir.",
    },
    {
      id: "hyrum",
      group: "state-parks",
      name: "Hyrum State Park",
      region: "Cache Valley",
      clue: "Shade trees, beaches, and a reservoir create a small Cache Valley retreat.",
    },
    {
      id: "jordan-river",
      group: "state-parks",
      name: "Jordan River Off-Highway Vehicle State Park",
      region: "Salt Lake City",
      clue: "Motocross tracks and a loop trail give riders several levels of challenge.",
    },
    {
      id: "jordanelle",
      group: "state-parks",
      name: "Jordanelle State Park",
      region: "Heber Valley",
      clue: "Hailstone, Rock Cliff, and Ross Creek offer different ways to enjoy one reservoir.",
    },
    {
      id: "kodachrome",
      group: "state-parks",
      name: "Kodachrome Basin State Park",
      region: "Kane County",
      clue: "Sixty-seven stone spires rise through bands of multicolored sandstone.",
    },
    {
      id: "lost-creek",
      group: "state-parks",
      name: "Lost Creek State Park",
      region: "Morgan County",
      clue: "A newer state park protects a quiet reservoir used for paddling, fishing, and camping.",
    },
    {
      id: "millsite",
      group: "state-parks",
      name: "Millsite State Park",
      region: "Near Ferron",
      clue: "Blue reservoir water sits below desert cliffs and routes into Ferron Canyon.",
    },
    {
      id: "otter-creek",
      group: "state-parks",
      name: "Otter Creek State Park",
      region: "Piute County",
      clue: "A quiet reservoir is known for trophy fishing, birding, and nearby ATV trails.",
    },
    {
      id: "palisade",
      group: "state-parks",
      name: "Palisade State Park",
      region: "Sanpete County",
      clue: "A reservoir, campground, and 18-hole golf course share a desert canyon setting.",
    },
    {
      id: "piute",
      group: "state-parks",
      name: "Piute State Park",
      region: "Sevier Plateau",
      clue: "A primitive reservoir beneath high cliffs is a quiet destination for trout fishing.",
    },
    {
      id: "quail-creek",
      group: "state-parks",
      name: "Quail Creek State Park",
      region: "Washington County",
      clue: "Warm water and a mild climate attract boaters and anglers throughout the year.",
    },
    {
      id: "red-fleet",
      group: "state-parks",
      name: "Red Fleet State Park",
      region: "Near Vernal",
      clue: "A trail leads to 200-million-year-old dinosaur tracks above a reservoir.",
    },
    {
      id: "rockport",
      group: "state-parks",
      name: "Rockport State Park",
      region: "Summit County",
      clue: "A northern Utah reservoir supports boating in summer and ice fishing in winter.",
    },
    {
      id: "sand-hollow",
      group: "state-parks",
      name: "Sand Hollow State Park",
      region: "Washington County",
      clue: "Warm blue reservoir water meets red sandstone and off-highway dunes.",
    },
    {
      id: "scofield",
      group: "state-parks",
      name: "Scofield State Park",
      region: "Carbon County",
      clue: "A high-elevation reservoir offers summer boating and winter ice fishing.",
    },
    {
      id: "snow-canyon",
      group: "state-parks",
      name: "Snow Canyon State Park",
      region: "Near St. George",
      clue: "Black lava flows contrast with red Navajo sandstone, dunes, and desert trails.",
    },
    {
      id: "steinaker",
      group: "state-parks",
      name: "Steinaker State Park",
      region: "Near Vernal",
      clue: "Sandy beaches and a Dinosaurland reservoir support boating, swimming, and fishing.",
    },
    {
      id: "territorial-statehouse",
      group: "state-parks",
      name: "Territorial Statehouse State Park Museum",
      region: "Fillmore",
      clue: "Utah’s oldest existing government building preserves its territorial-era story.",
    },
    {
      id: "heritage-park",
      group: "state-parks",
      name: "This Is The Place Heritage Park",
      region: "Salt Lake City",
      clue: "Historic buildings and interpreters recreate parts of Utah’s pioneer-era life.",
    },
    {
      id: "field-house",
      group: "state-parks",
      name: "Utah Field House of Natural History State Park Museum",
      region: "Vernal",
      clue: "Fossils, hands-on exhibits, and a dinosaur garden explain the region’s deep past.",
    },
    {
      id: "utah-lake",
      group: "state-parks",
      name: "Utah Lake State Park",
      region: "Provo",
      clue: "A marina and campground provide access to Utah’s largest freshwater lake.",
    },
    {
      id: "utahraptor",
      group: "state-parks",
      name: "Utahraptor State Park",
      region: "Near Moab",
      clue: "A new park protects recreation land and important dinosaur fossil resources.",
    },
    {
      id: "wasatch-mountain",
      group: "state-parks",
      name: "Wasatch Mountain State Park",
      region: "Near Midway",
      clue: "Mountain trails, camping, golf, skiing, and snowshoeing make this a four-season park.",
    },
    {
      id: "willard-bay",
      group: "state-parks",
      name: "Willard Bay State Park",
      region: "Box Elder County",
      clue: "Two marinas serve a freshwater reservoir separated from the Great Salt Lake.",
    },
    {
      id: "yuba",
      group: "state-parks",
      name: "Yuba State Park",
      region: "Central Utah",
      clue: "Warm water, sandy beaches, and boat-in camping define this central Utah reservoir.",
    },
  ];
})();
