(function () {
  "use strict";

  window.UTAH_SYMBOLS = Object.freeze([
    { id: "symbol-01", group: "nature", label: "State animal", name: "Rocky Mountain elk", year: 1971, image: "rocky-mountain-elk.png" },
    { id: "symbol-02", group: "nature", label: "State bird", name: "California gull", year: 1955, image: "california-gull.png" },
    { id: "symbol-03", group: "nature", label: "State flower", name: "Sego lily", year: 1911, image: "sego-lily.png" },
    { id: "symbol-04", group: "nature", label: "State tree", name: "Quaking aspen", year: 2014, image: "quaking-aspen.png" },
    { id: "symbol-05", group: "nature", label: "State insect", name: "Honey bee", year: 1983, image: "honey-bee.png" },
    { id: "symbol-06", group: "nature", label: "State fish", name: "Bonneville cutthroat trout", year: 1997, image: "bonneville-cutthroat-trout.png" },
    { id: "symbol-07", group: "nature", label: "State gem", name: "Topaz", year: 1969, image: "topaz.png" },
    { id: "symbol-08", group: "nature", label: "State mineral", name: "Copper", year: 1994, image: "copper.png" },
    { id: "symbol-09", group: "nature", label: "State fossil", name: "Allosaurus", year: 1988, image: "allosaurus.png" },
    { id: "symbol-10", group: "nature", label: "State fruit", name: "Cherry", year: 1997, image: "cherry.png" },
    { id: "symbol-11", group: "nature", label: "State vegetable", name: "Spanish sweet onion", year: 2002, image: "spanish-sweet-onion.png" },
    { id: "symbol-12", group: "nature", label: "State historic vegetable", name: "Sugar beet", year: 2002, image: "sugar-beet.png" },
    { id: "symbol-13", group: "nature", label: "State grass", name: "Indian ricegrass", year: 1990, image: "indian-ricegrass.png" },
    { id: "symbol-14", group: "nature", label: "State mushroom", name: "Porcini", year: 2023, image: "porcini.png" },
    { id: "symbol-15", group: "culture", label: "State song", name: "Utah, This Is the Place", year: 2003, image: "state-song.png", visual: false, musical: true },
    { id: "symbol-16", group: "culture", label: "State hymn", name: "Utah, We Love Thee", year: 2003, image: "state-hymn.png", visual: false, musical: true },
    { id: "symbol-17", group: "heritage", label: "State motto", name: "Industry", year: 1959, image: "industry.png" },
    { id: "symbol-18", group: "heritage", label: "State emblem", name: "Beehive", year: 1959, image: "beehive.png" },
    { id: "symbol-19", group: "culture", label: "State work of land art", name: "Spiral Jetty", year: 2017, image: "spiral-jetty.png" },
    { id: "symbol-20", group: "nature", label: "State centennial astronomical symbol", name: "Beehive Cluster", year: 1996, image: "beehive-cluster.png" },
    { id: "symbol-21", group: "culture", label: "State winter sports", name: "Skiing and snowboarding", year: 2012, image: "skiing-snowboarding.png" },
    { id: "symbol-22", group: "nature", label: "State stone", name: "Honeycomb calcite", year: 2021, image: "honeycomb-calcite.png" },
    { id: "symbol-23", group: "heritage", label: "State seal", name: "The Great Seal of the State of Utah", year: 1896, image: "great-seal.png" },
    { id: "symbol-24", group: "nature", label: "State rock", name: "Coal", year: 1991, image: "coal.png" },
    { id: "symbol-25", group: "nature", label: "State reptile", name: "Gila monster", year: 2019, image: "gila-monster.png" },
    { id: "symbol-26", group: "heritage", label: "State railroad museum", name: "Ogden Union Station", year: 1988, image: "ogden-union-station.png" },
    { id: "symbol-27", group: "heritage", label: "State military museum", name: "Fort Douglas Military Museum", year: 2020, image: "fort-douglas.png" },
    { id: "symbol-28", group: "culture", label: "State works of art", name: "Native American rock art", year: 2017, image: "native-american-rock-art.png" },
    { id: "symbol-29", group: "heritage", label: "State historic flag", name: "Historic Utah state flag", year: 2023, image: "historic-state-flag.png" },
    { id: "symbol-30", group: "heritage", label: "State flag", name: "Utah state flag", year: 2024, image: "utah-state-flag.png" },
    { id: "symbol-31", group: "heritage", label: "State firearm", name: "M1911 automatic pistol", year: 2011, image: "m1911.png" },
    { id: "symbol-32", group: "heritage", label: "State emblem of service and sacrifice", name: "Honor and Remember Flag", year: 2011, image: "honor-remember-flag.png" },
    { id: "symbol-33", group: "nature", label: "State dinosaur", name: "Utahraptor", year: 2018, image: "utahraptor.png" },
    { id: "symbol-34", group: "heritage", label: "State demonym", name: "Utahn", year: 2025, image: "utahn.png" },
    { id: "symbol-35", group: "nature", label: "State crustacean", name: "Artemia franciscana (brine shrimp)", year: 2023, image: "brine-shrimp.png" },
    { id: "symbol-36", group: "culture", label: "State cooking pot", name: "Dutch oven", year: 1997, image: "dutch-oven.png" },
    { id: "symbol-37", group: "culture", label: "State centennial tartan", name: "Utah Centennial Tartan", year: 1997, image: "utah-centennial-tartan.png" },
    { id: "symbol-38", group: "nature", label: "State centennial star", name: "Dubhe", year: 1996, image: "dubhe.png" },
    { id: "symbol-39", group: "nature", label: "State bird of prey", name: "Golden eagle", year: 2022, image: "golden-eagle.png" },
    { id: "symbol-40", group: "culture", label: "State folk dance", name: "Square dance", year: 1994, image: "square-dance.png" }
  ]);
})();
